### ISSUE TITLE
Add onboarding to MTA

### ISSUE THREAD

**Issue by weidingergerald** [AnotherCodeArtist/medien-transparenz.at#109]
Joyride | http://zurb.com/playground/jquery-joyride-feature-tour-plugin
Intro.js | http://usablica.github.io/intro.js/
Hopscotch | http://linkedin.github.io/hopscotch/
Crumble | http://blog.tommoor.com/crumble/
Pageguide | http://tracelytics.github.io/pageguide/
Bootstro.js | http://clu3.github.io/bootstro.js/
https://github.com/jordanburke/angular-help-overlay

**Comment by relative-progressio** [comment]
Used [intro.js](http://introjs.com/) for implementation, since it is somehow in active development and has the [angular directive ](http://code.mendhak.com/angular-intro.js) available.

With selecting the class node (`#node`), nothing of the flow-diagram was selected, so it is not possible to access the parts of the diagram. Therefore, the hints were otherwise structured.

Apparently  the databinding is not part of the directive, so it is not possible to trigger the autostart of the onboarding via scope variable. Therefore, the intro is started with clicking the button on the right side.
