### ISSUE TITLE
Bugfix: Search Controller Grouping Error

### ISSUE THREAD

**Issue by weidingergerald** [AnotherCodeArtist/medien-transparenz.at#158]
The search method which is used for getting the server side organisations and media has a serious issue regarding grouping which has an impact on multiple areas of the application.

See:
http://i.imgur.com/Sr48bdE.jpg
http://i.imgur.com/fLDEMO2.jpg

**Comment by relative-progressio** [comment]
The media entries were multiplied because of the fact that the entry recived money from different organisation types. Therefore, the grouping is now organisation only. Please do not forget to clear the session storage. Comes with [release-sprint-12 branch](https://github.com/AnotherCodeArtist/medien-transparenz.at/tree/release-sprint-12).

(relates to #153, #97)
